// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxyLGoHxQfSLOtVWU5PPZG9W2ILO9kfjk',
    appId: '1:949084502977:web:5df9e6069458eba7488d40',
    messagingSenderId: '949084502977',
    projectId: 'flit-crud-cf324',
    authDomain: 'flit-crud-cf324.firebaseapp.com',
    storageBucket: 'flit-crud-cf324.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqMTaRsWZa2M7D7QcHhf3q9Jqc7JifXrU',
    appId: '1:949084502977:android:c9a357e93e28697b488d40',
    messagingSenderId: '949084502977',
    projectId: 'flit-crud-cf324',
    storageBucket: 'flit-crud-cf324.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3MsFwqS2NY2dQQNgoZ7pp-cqDN6xwBUo',
    appId: '1:949084502977:ios:30c76fc189092271488d40',
    messagingSenderId: '949084502977',
    projectId: 'flit-crud-cf324',
    storageBucket: 'flit-crud-cf324.appspot.com',
    androidClientId: '949084502977-blvpnegt92icui89jdh475mint3me32m.apps.googleusercontent.com',
    iosClientId: '949084502977-f3na7t778cfrc35qub4m8fnf000ie0kn.apps.googleusercontent.com',
    iosBundleId: 'com.example.notesApp',
  );
}
